# Docker compose for RapidAnnotator
# Raúl Sánchez <raul@um.es>

version: '3'

services:
  rapidannotator:
    build: .
    hostname: labyrinth01.inf.um.es
    ports:
      # external 80 port mapped to internal 8000 port
      - "8888:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rapidannotator
      MYSQL_USER: rapidannotator
      MYSQL_PASSWORD: rapidannotator

